update

diff --git a/lampi b/lampi
--- a/lampi
+++ b/lampi
@@ -3,7 +3,7 @@ p_name=lampi
 p_author='Md Jahidul Hamid'
 p_source='https://github.com/neurobin/lampi'
 p_bugt="$p_source/issues"
-p_version=0.1.2
+p_version=0.1.3
 ver_info="
 Name        : $p_name
 Version     : $p_version
@@ -150,7 +150,7 @@ Uninstall       : $uninstall
 Reinstall       : $reinstall
 NoUpdate        : $no_update
 "
-echo "$opts"
+#echo "$opts"
 
 
 #check for root
@@ -164,8 +164,6 @@ if [ ! -z "$SUDO_USER" ]; then
     user="$SUDO_USER"
 fi
 mkdir -p "$dr"
-chown $user:$user "$dr"
-chmod 755 "$dr"
 
 #extract dist version
 rel=(`lsb_release -r | grep -o '[0-9]\+'`)
@@ -241,16 +239,17 @@ else
              fi
              
         done
-        pdconf=/etc/phpmyadmin/apache.conf
-        pdincl="Include $pdconf"
-        if ! grep -s -e "$pdincl" "$aconf" >/dev/null 2>&1; then
-            sed -i.bak "$ a $pdincl" "$aconf" &&
-            printf "\n\t apache2 conf modified to include phpmyadmin\n" ||
-            printf "\n\tE: failed to modify apache2 conf for phpmyadmin\n"
-        else
-            printf "\n\tphpmyadmin is already added in apache2 conf (skipped)\n"
+        if ! $npa; then
+            pdconf=/etc/phpmyadmin/apache.conf
+            pdincl="Include $pdconf"
+            if ! grep -s -e "$pdincl" "$aconf" >/dev/null 2>&1; then
+                sed -i.bak "$ a $pdincl" "$aconf" &&
+                printf "\n\t apache2 conf modified to include phpmyadmin\n" ||
+                printf "\n\tE: failed to modify apache2 conf for phpmyadmin\n"
+            else
+                printf "\n\tphpmyadmin is already added in apache2 conf (skipped)\n"
+            fi
         fi
-
         apt-get autoremove
         
         if ! $uninstall; then
@@ -270,92 +269,85 @@ else
 
     #create info.php
     [ ! -f "$dr"/info.php ] && echo "$tphp" > "$dr"/info.php && printf "\n\tinfo.php created\n" || printf "\n\tinfo.php exists (skipped)\n"
-    chown $user:$user "$dr"/info.php
+    
+    chown -R $user:$user "$dr"
 
-if $npa; then
-    sed -i.bak -e 's#^[[:blank:]]*Include[[:blank:]]*/etc/phpmyadmin/apache.conf[[:blank:]]*.*##' "$aconf"
-fi
+    if $npa; then
+        sed -i.bak -e 's#^[[:blank:]]*Include[[:blank:]]*/etc/phpmyadmin/apache.conf[[:blank:]]*.*##' "$aconf"
+    fi
 
-    dire_opts="\n\t\tAllowOverride All\n\t\tOptions Indexes FollowSymLinks MultiViews\n\t\tOrder allow,deny\n\t\tRequire all granted\n\t\tAllow from all\n\t\t\n\t"
-    dire_opts_ssl="\n\t\t\tAllowOverride All\n\t\t\tOptions Indexes FollowSymLinks MultiViews\n\t\t\tOrder allow,deny\n\t\t\tRequire all granted\n\t\t\tAllow from all\n\t\t\tSSLOptions +StdEnvVars\n\t\t\t\n\t\t"
-    dire="\t<Directory $dr>$dire_opts</Directory>\n"
-
+get_exec_path(){
+    p="$(type "$1" | sed -n -e "s#.*[[:blank:]]\([^[:blank:]]*$1\)[[:blank:]]*\$#\1#p")"
+    if [ -n "$p" ]; then
+        echo "$p"
+    else
+        echo "$1"
+    fi
+}
+    
     #custom sites
-    ds='/etc/apache2/sites-available/000-default.conf'
-    ds_ssl='/etc/apache2/sites-available/default-ssl.conf'
-    dsn="$(dirname "$ds")/$localhost.conf"
-    ds_ssln="$(dirname "$ds_ssl")/$localhost-ssl.conf"
+    bdir='/etc/apache2/sites-available'
+    dsn="$bdir/$localhost.conf"
+    dsln="$bdir/$localhost-ssl.conf"
 
-    if [ "$ds" = "$dsn" ]; then
-        printf "$ds\m\t\tand\n$dsn\n\t\tcan not be same\nE: ServerName: $(basename "$ds") not allowed\n"
+    CGIROOT="$(dirname "$(get_exec_path php-cgi)")"
+    
+    http="<VirtualHost *:80>
+            ServerAlias $localhost
+            ServerAdmin admin@$localhost
+            
+            DocumentRoot $dr
+            <Directory />
+                    Options FollowSymLinks
+                    AllowOverride All
+            </Directory>
+            <Directory $dr >
+                    Options Indexes FollowSymLinks MultiViews
+                    AllowOverride All
+                    Order allow,deny
+                    allow from all
+            </Directory>
+		    # Configure PHP as CGI
+		    ScriptAlias /local-bin $CGIROOT
+		    DirectoryIndex index.php index.html
+		    AddType application/x-httpd-php5 .php
+		    Action application/x-httpd-php5 /local-bin/php-cgi
+    </VirtualHost>"
+    
+    https="<VirtualHost *:443>
+            ServerAlias $localhost
+            ServerAdmin admin@$localhost
+            
+            DocumentRoot $dr
+            <Directory />
+                    Options FollowSymLinks
+                    AllowOverride All
+            </Directory>
+            <Directory $dr >
+                    Options Indexes FollowSymLinks MultiViews
+                    AllowOverride All
+                    Order allow,deny
+                    allow from all
+            </Directory>
+		    # Configure PHP as CGI
+		    ScriptAlias /local-bin $CGIROOT
+		    DirectoryIndex index.php index.html
+		    AddType application/x-httpd-php5 .php
+		    Action application/x-httpd-php5 '/local-bin/php-cgi'
+		    
+		    # Configure SSL
+		    SSLEngine on
+		    SSLCertificateFile	/etc/ssl/certs/ssl-cert-snakeoil.pem
+		    SSLCertificateKeyFile /etc/ssl/private/ssl-cert-snakeoil.key
+    </VirtualHost>"
+
+    if [ "$dsn" = "$dsln" ]; then
+        printf "$dsn\m\t\tand\n$dsln\n\t\tcan not be same\nE: ServerName: $(basename "$dsn") not allowed\n"
         exit 1
-    elif [ "$ds_ssl" = "$ds_ssln" ]; then
-        printf "$ds_ssl\m\t\tand\n$ds_ssln\n\t\tcan not be same\nE: ServerName: default not allowed\n"
-        exit 1
     fi
 
-    export localhost
-    export dr
-    export dire
-    copy_default_config(){
-        sed  -e "s=^\([[:blank:]]*DocumentRoot\).*$=\1 $dr="\
-                   -e "s=^\([[:blank:]]*ServerName\).*$=\1 $localhost="\
-                   -e "s=^\([[:blank:]]*<[[:blank:]]*Directory[[:blank:]]*\)[^[:blank:]]\+\([[:blank:]]*>[[:blank:]]*\)$=\1$dr\2="\
-                   -e "s=^\([[:blank:]]*<[[:blank:]]*VirtualHost[[:blank:]]*\)[^:]*\(:[^>]*>[[:blank:]]*\)$=\1 127.0.0.1\2="\
-                   "$1" > "$2" &&
-        printf "\n\tcopied $1 --> $2 with required modifications\n" ||
-        printf "\n\tE: Failed to copy $1 --> $2\n"
-    }
 
-    if ! $ssl_only; then
-        copy_default_config "$ds" "$dsn"
-    fi
-    if $ssl; then
-        copy_default_config "$ds_ssl" "$ds_ssln"
-    fi
-
-    insert_server_property(){
-        if ! grep -s -e "^\([[:blank:]]*$1\).*$" "$2" >/dev/null 2>&1; then
-            sed -i.bak -e "s=^[[:blank:]]*<[[:blank:]]*VirtualHost[[:blank:]]*.*>[[:blank:]]*$=&\n\tServerName $localhost=" "$2" &&
-            printf "\n\tSuccessfully inserted $1 to $2\n" ||
-            printf "\n\tE: Failed to insert $1 to $2\n"
-        else
-            printf "\n\t$1 exists in $2 (skipped)\n"
-        fi
-    }
-    if ! $ssl_only; then
-        insert_server_property ServerName "$dsn"
-    fi
-    if $ssl; then
-        insert_server_property ServerName "$ds_ssln"
-    fi
-
-    insert_docroot_property(){
-        if ! grep -s -e "^[[:blank:]]*<[[:blank:]]*Directory[[:blank:]]*[^[:blank:]]\+[[:blank:]]*>[[:blank:]]*$" "$1" >/dev/null 2>&1; then
-            sed -i.bak -e "s=^\([[:blank:]]*\)DocumentRoot.*$=&\n$dire=" "$1" &&
-            printf "\n\tSuccessfully inserted DocumentRoot in $1\n" ||
-            printf "\n\tE: Failed to insert DocumentRoot in $1\n"
-        else
-            cat "${1-x}" > "${1-x}.bak" 2>&1 &&
-            printf "\n\tBack up: ${1-x} succeded\n" ||
-            printf "\n\tE: Back up: ${1-x} failed\n"
-            echo "$(awk '
-            BEGIN       {p=1}
-            /^[[:blank:]]*<[[:blank:]]*Directory[[:blank:]]*[^[:blank:]]+[[:blank:]]*>[[:blank:]]*/   {print;print "'"$dire_opts_ssl"'";p=0}
-            /[^#]*<\/Directory/     {p=1}
-            p' "${1-x}")" > "${1-x}" &&
-            printf "\n\tSuccessfully edited ${1-x}\n" ||
-            printf "\n\tE: Failed to edit ${1-x}\n"
-        fi
-    }
-
-    if ! $ssl_only; then
-        insert_docroot_property "$dsn"
-    fi
-    if $ssl; then
-        insert_docroot_property "$ds_ssln"
-    fi
-
+    #manage /etc/hosts
     if ! grep -s -e "^127.0.0.1[[:blank:]]*$localhost[[:blank:]]*$" /etc/hosts >/dev/null 2>&1; then
         sed -i.bak -e "1 a 127.0.0.1\t$localhost" /etc/hosts &&
         printf "\n\tAdded $localhost to /etc/hosts\n" ||
@@ -363,6 +355,10 @@ fi
     fi
 
     #enable mods
+    a2enmod actions &&
+    printf "\n\tEnabled mod_actions" ||
+    printf "\n\tD: Failed to enable mod_actions"
+    
     a2enmod rewrite &&
     printf "\n\tEnabled mod_rewrite\n" || 
     printf "\n\tE: Failed to enable mod_rewrite\n"
@@ -373,27 +369,25 @@ fi
     fi
 
     #enable sites
-    if ! $ssl_only; then
-        a2ensite "$localhost" &&
-        printf "\n\tEnabled $localhost\n" ||
-        printf "\n\tE: Failed to enable $localhost\n"
-    fi
-    if $ssl; then 
-        a2ensite "$localhost"-ssl &&
-        printf "\n\tEnabled $localhost-ssl\n" ||
-        printf "\n\tE: Failed to enable $localhost-ssl\n"
-    fi
-
+    
     endm="$endm
     ******* Visit Site *******
         "
     if ! $ssl_only; then
         endm="${endm}http://$localhost/info.php
         "
+        echo "$http" > "$dsn"
+        a2ensite "$localhost" &&
+        printf "\n\tEnabled $localhost\n" ||
+        printf "\n\tE: Failed to enable $localhost\n"
     fi
     if $ssl; then 
         endm="${endm}https://$localhost/info.php
         "
+        echo "$https" > "$dsln"
+        a2ensite "$localhost"-ssl &&
+        printf "\n\tEnabled $localhost-ssl\n" ||
+        printf "\n\tE: Failed to enable $localhost-ssl\n"
     fi
 fi
 
