update

diff --git a/lampi b/lampi
--- a/lampi
+++ b/lampi
@@ -3,7 +3,7 @@ p_name=lampi
 p_author='Md Jahidul Hamid'
 p_source='https://github.com/neurobin/lampi'
 p_bugt="$p_source/issues"
-p_version=0.1.3
+p_version=0.1.4
 ver_info="
 Name        : $p_name
 Version     : $p_version
@@ -22,19 +22,19 @@ help="
 # with default configs
 #
 # Options:
-#   [ -i, --install ]       : install LAMP
-#   [ -ri, --reinstall ]    : reinstall LAMP
-#   [ -u, --uninstall ]     : uninstall LAMP
-#   [ -rm, --remove ]       : remove a site
-#   [ -f, --force ]         : force (remove directory)
-#   [ -nu, --no-update ]    : do not run apt-get update
-#   [ -s, --ssl ]           : enable SSL   
-#   [ -so, --ssl-only ]     : configure for https site only 
-#   [ -n, --name ]          : server name (default localhost)
-#   [ -dr, --doc-root ]     : arbitrary document root
-#   [ -npa, --no-php-myadmin: no php my admin
-#   [ -v, --version ]       : show version info
-#   [ -h, --help ]          : show help 
+#   [ -i, --install ]           : install LAMP
+#   [ -ri, --reinstall ]        : reinstall LAMP
+#   [ -u, --uninstall ]         : uninstall LAMP
+#   [ -rm, --remove ]           : remove a site
+#   [ -f, --force ]             : force (remove directory)
+#   [ -nu, --no-update ]        : do not run apt-get update
+#   [ -s, --ssl ]               : enable SSL   
+#   [ -so, --ssl-only ]         : configure for https site only 
+#   [ -n, --name ]              : server name (default localhost)
+#   [ -dr, --doc-root ]         : arbitrary document root
+#   [ -npa, --no-php-myadmin ]  : no php my admin
+#   [ -v, --version ]           : show version info
+#   [ -h, --help ]              : show help 
 ##############################################################
 "
 dr=''
@@ -164,16 +164,14 @@ if [ ! -z "$SUDO_USER" ]; then
     user="$SUDO_USER"
 fi
 mkdir -p "$dr"
+chown $user:$user "$dr"
+chmod 755 "$dr"
 
 #extract dist version
 rel=(`lsb_release -r | grep -o '[0-9]\+'`)
 rv=${rel[0]}
 
-tphp='
-<?php
-phpinfo();
-?>
-'
+tphp='<?php phpinfo(); ?>'
 endm="
 ****** Successfully reloaded apache2 ******
 "
@@ -182,12 +180,16 @@ aconf=/etc/apache2/apache2.conf
 
 if [ -n "$remove" ]; then
     a2dissite $remove
-    remove_file=/etc/apache2/sites-available/"$remove.conf"
-    rm_dir="$(sed -n -e 's/^[[:blank:]]*DocumentRoot[[:blank:]]*\([^#]*\).*/\1/p' "$remove_file")"
-    if $force; then
+    remove_file=/etc/apache2/sites-available/"$remove"
+    rm_dir="$(sed -n -e 's/^[[:blank:]]*DocumentRoot[[:blank:]]*\([^#]*\).*/\1/p' "$remove_file.conf")"
+    if $force && ! test -z "$rm_dir" && [ "." != "$rm_dir" ] && [ '..' != "$rm_dir" ]; then
         rm -r "$rm_dir"
     fi
-    rm "$remove_file"
+    rm "$remove_file.conf" "$remove_file.conf.bak"
+    if $ssl; then
+        a2dissite $remove-ssl
+        rm "$remove_file-ssl.conf" "$remove_file-ssl.conf.bak"
+    fi
 else
     if $install || $uninstall; then
 
@@ -219,7 +221,11 @@ else
         list+=("$mysql")
 
         #phpmyadmin
-        phpmd='phpmyadmin apache2-utils'
+        if ! $npa; then
+            phpmd='phpmyadmin apache2-utils'
+        else
+            phpmd=''
+        fi
         if (( $rv >= 16 ));then
             phpmd="$phpmd php-gettext php-mbstring"
         fi
@@ -239,7 +245,7 @@ else
              fi
              
         done
-        if ! $npa; then
+        if ! $npa; then 
             pdconf=/etc/phpmyadmin/apache.conf
             pdincl="Include $pdconf"
             if ! grep -s -e "$pdincl" "$aconf" >/dev/null 2>&1; then
@@ -250,6 +256,7 @@ else
                 printf "\n\tphpmyadmin is already added in apache2 conf (skipped)\n"
             fi
         fi
+
         apt-get autoremove
         
         if ! $uninstall; then
@@ -269,85 +276,89 @@ else
 
     #create info.php
     [ ! -f "$dr"/info.php ] && echo "$tphp" > "$dr"/info.php && printf "\n\tinfo.php created\n" || printf "\n\tinfo.php exists (skipped)\n"
-    
-    chown -R $user:$user "$dr"
+    chown $user:$user "$dr"/info.php
 
-    if $npa; then
-        sed -i.bak -e 's#^[[:blank:]]*Include[[:blank:]]*/etc/phpmyadmin/apache.conf[[:blank:]]*.*##' "$aconf"
-    fi
+    dire_opts="\n\t\tAllowOverride All\n\t\tOptions Indexes FollowSymLinks MultiViews\n\t\tOrder allow,deny\n\t\tRequire all granted\n\t\tAllow from all\n\t\t\n\t"
+    dire="\t<Directory $dr>$dire_opts</Directory>\n"
 
-get_exec_path(){
-    p="$(type "$1" | sed -n -e "s#.*[[:blank:]]\([^[:blank:]]*$1\)[[:blank:]]*\$#\1#p")"
-    if [ -n "$p" ]; then
-        echo "$p"
-    else
-        echo "$1"
-    fi
-}
-    
     #custom sites
-    bdir='/etc/apache2/sites-available'
-    dsn="$bdir/$localhost.conf"
-    dsln="$bdir/$localhost-ssl.conf"
+    sites_av=/etc/apache2/sites-available
+    ds="$(find "$sites_av" -name '*default.conf')"
+    ds_ssl="$(find "$sites_av" -name '*default*ssl*.conf')"
+    dsn="$sites_av/$localhost.conf"
+    ds_ssln="$sites_av/$localhost-ssl.conf"
 
-    CGIROOT="$(dirname "$(get_exec_path php-cgi)")"
-    
-    http="<VirtualHost *:80>
-            ServerAlias $localhost
-            ServerAdmin admin@$localhost
-            
-            DocumentRoot $dr
-            <Directory />
-                    Options FollowSymLinks
-                    AllowOverride All
-            </Directory>
-            <Directory $dr >
-                    Options Indexes FollowSymLinks MultiViews
-                    AllowOverride All
-                    Order allow,deny
-                    allow from all
-            </Directory>
-		    # Configure PHP as CGI
-		    ScriptAlias /local-bin $CGIROOT
-		    DirectoryIndex index.php index.html
-		    AddType application/x-httpd-php5 .php
-		    Action application/x-httpd-php5 /local-bin/php-cgi
-    </VirtualHost>"
-    
-    https="<VirtualHost *:443>
-            ServerAlias $localhost
-            ServerAdmin admin@$localhost
-            
-            DocumentRoot $dr
-            <Directory />
-                    Options FollowSymLinks
-                    AllowOverride All
-            </Directory>
-            <Directory $dr >
-                    Options Indexes FollowSymLinks MultiViews
-                    AllowOverride All
-                    Order allow,deny
-                    allow from all
-            </Directory>
-		    # Configure PHP as CGI
-		    ScriptAlias /local-bin $CGIROOT
-		    DirectoryIndex index.php index.html
-		    AddType application/x-httpd-php5 .php
-		    Action application/x-httpd-php5 '/local-bin/php-cgi'
-		    
-		    # Configure SSL
-		    SSLEngine on
-		    SSLCertificateFile	/etc/ssl/certs/ssl-cert-snakeoil.pem
-		    SSLCertificateKeyFile /etc/ssl/private/ssl-cert-snakeoil.key
-    </VirtualHost>"
-
-    if [ "$dsn" = "$dsln" ]; then
-        printf "$dsn\m\t\tand\n$dsln\n\t\tcan not be same\nE: ServerName: $(basename "$dsn") not allowed\n"
+    if [ "$ds" = "$dsn" ]; then
+        printf "$ds\m\t\tand\n$dsn\n\t\tcan not be same\nE: ServerName: $(basename "$ds") not allowed\n"
+        exit 1
+    elif [ "$ds_ssl" = "$ds_ssln" ]; then
+        printf "$ds_ssl\m\t\tand\n$ds_ssln\n\t\tcan not be same\nE: ServerName: default not allowed\n"
         exit 1
     fi
 
+    export localhost
+    export dr
+    export dire
+    copy_default_config(){
+        sed  -e "s=^\([[:blank:]]*DocumentRoot\).*$=\1 $dr="\
+                   -e "s=^\([[:blank:]]*ServerName\).*$=\1 $localhost="\
+                   -e "s=^\([[:blank:]]*<[[:blank:]]*Directory[[:blank:]]*\)[^[:blank:]]\+\([[:blank:]]*>[[:blank:]]*\)$=\1$dr\2="\
+                   -e "s=^\([[:blank:]]*<[[:blank:]]*VirtualHost[[:blank:]]*\)[^:]*\(:[^>]*>[[:blank:]]*\)$=\1 127.0.0.1\2="\
+                   "$1" > "$2" &&
+        printf "\n\tcopied $1 --> $2 with required modifications\n" ||
+        printf "\n\tE: Failed to copy $1 --> $2\n"
+    }
 
-    #manage /etc/hosts
+    if ! $ssl_only; then
+        copy_default_config "$ds" "$dsn"
+    fi
+    #no else
+    if $ssl; then
+        copy_default_config "$ds_ssl" "$ds_ssln"
+    fi
+
+    insert_server_property(){
+        if ! grep -s -e "^\([[:blank:]]*$1\).*$" "$2" >/dev/null 2>&1; then
+            sed -i.bak -e "s=^[[:blank:]]*<[[:blank:]]*VirtualHost[[:blank:]]*.*>[[:blank:]]*$=&\n\tServerName $localhost=" "$2" &&
+            printf "\n\tSuccessfully inserted $1 to $2\n" ||
+            printf "\n\tE: Failed to insert $1 to $2\n"
+        else
+            printf "\n\t$1 exists in $2 (skipped)\n"
+        fi
+    }
+    if ! $ssl_only; then
+        insert_server_property ServerName "$dsn"
+    fi
+    if $ssl; then
+        insert_server_property ServerName "$ds_ssln"
+    fi
+
+    insert_docroot_property(){
+        if ! grep -s -e "^[[:blank:]]*<[[:blank:]]*Directory[[:blank:]]*[^[:blank:]]\+[[:blank:]]*>[[:blank:]]*$" "$1" >/dev/null 2>&1; then
+            sed -i.bak -e "s=^\([[:blank:]]*\)DocumentRoot.*$=&\n$dire=" "$1" &&
+            printf "\n\tSuccessfully inserted DocumentRoot in $1\n" ||
+            printf "\n\tE: Failed to insert DocumentRoot in $1\n"
+        else
+            cat "${1-x}" > "${1-x}.bak" 2>&1 &&
+            printf "\n\tBack up: ${1-x} succeded\n" ||
+            printf "\n\tE: Back up: ${1-x} failed\n"
+            echo "$(awk '
+            BEGIN       {p=1}
+            /^[[:blank:]]*<[[:blank:]]*Directory[[:blank:]]*[^[:blank:]]+[[:blank:]]*>[[:blank:]]*/   {print;print "'"$dire_opts"'";p=0}
+            /[^#]*<\/Directory/     {p=1}
+            p' "${1-x}")" > "${1-x}" &&
+            printf "\n\tSuccessfully edited ${1-x}\n" ||
+            printf "\n\tE: Failed to edit ${1-x}\n"
+        fi
+    }
+
+    if ! $ssl_only; then
+        insert_docroot_property "$dsn"
+    fi
+    if $ssl; then
+        insert_docroot_property "$ds_ssln"
+    fi
+
     if ! grep -s -e "^127.0.0.1[[:blank:]]*$localhost[[:blank:]]*$" /etc/hosts >/dev/null 2>&1; then
         sed -i.bak -e "1 a 127.0.0.1\t$localhost" /etc/hosts &&
         printf "\n\tAdded $localhost to /etc/hosts\n" ||
@@ -355,10 +366,6 @@ get_exec_path(){
     fi
 
     #enable mods
-    a2enmod actions &&
-    printf "\n\tEnabled mod_actions" ||
-    printf "\n\tD: Failed to enable mod_actions"
-    
     a2enmod rewrite &&
     printf "\n\tEnabled mod_rewrite\n" || 
     printf "\n\tE: Failed to enable mod_rewrite\n"
@@ -369,25 +376,27 @@ get_exec_path(){
     fi
 
     #enable sites
-    
+    if ! $ssl_only; then
+        a2ensite "$localhost" &&
+        printf "\n\tEnabled $localhost\n" ||
+        printf "\n\tE: Failed to enable $localhost\n"
+    fi
+    if $ssl; then 
+        a2ensite "$localhost"-ssl &&
+        printf "\n\tEnabled $localhost-ssl\n" ||
+        printf "\n\tE: Failed to enable $localhost-ssl\n"
+    fi
+
     endm="$endm
     ******* Visit Site *******
         "
     if ! $ssl_only; then
         endm="${endm}http://$localhost/info.php
         "
-        echo "$http" > "$dsn"
-        a2ensite "$localhost" &&
-        printf "\n\tEnabled $localhost\n" ||
-        printf "\n\tE: Failed to enable $localhost\n"
     fi
     if $ssl; then 
         endm="${endm}https://$localhost/info.php
         "
-        echo "$https" > "$dsln"
-        a2ensite "$localhost"-ssl &&
-        printf "\n\tEnabled $localhost-ssl\n" ||
-        printf "\n\tE: Failed to enable $localhost-ssl\n"
     fi
 fi
 
