update

diff --git a/lampi b/lampi
--- a/lampi
+++ b/lampi
@@ -3,7 +3,7 @@ p_name=lampi
 p_author='Md Jahidul Hamid'
 p_source='https://github.com/neurobin/lampi'
 p_bugt="$p_source/issues"
-p_version=0.1.4
+p_version=0.1.5
 ver_info="
 Name        : $p_name
 Version     : $p_version
@@ -33,6 +33,7 @@ help="
 #   [ -n, --name ]              : server name (default localhost)
 #   [ -dr, --doc-root ]         : arbitrary document root
 #   [ -npa, --no-php-myadmin ]  : no php my admin
+#   [ -nsr, --no-server-restart]: no server restart
 #   [ -v, --version ]           : show version info
 #   [ -h, --help ]              : show help 
 ##############################################################
@@ -48,6 +49,7 @@ reinstall=false
 remove=
 force=false
 npa=false
+nsr=false
 for op in "$@";do
     case "$op" in
         -v|--version)
@@ -85,6 +87,10 @@ for op in "$@";do
             ;;
         -npa|--no-php-myadmin)
             npa=true
+            shift
+            ;;
+        -nsr|--no-server-restart)
+            nsr=true
             shift
             ;;
         -i|--install)
@@ -181,9 +187,12 @@ aconf=/etc/apache2/apache2.conf
 if [ -n "$remove" ]; then
     a2dissite $remove
     remove_file=/etc/apache2/sites-available/"$remove"
-    rm_dir="$(sed -n -e 's/^[[:blank:]]*DocumentRoot[[:blank:]]*\([^#]*\).*/\1/p' "$remove_file.conf")"
-    if $force && ! test -z "$rm_dir" && [ "." != "$rm_dir" ] && [ '..' != "$rm_dir" ]; then
-        rm -r "$rm_dir"
+    sed -i .bak -e "/127.0.0.1[[:blank:]]*$remove/d" /etc/hosts
+    if [ -f "$remove_file.conf" ]; then
+        rm_dir="$(sed -n -e 's/^[[:blank:]]*DocumentRoot[[:blank:]]*\([^#]*\).*/\1/p' "$remove_file.conf")"
+        if $force && ! test -z "$rm_dir" && [ "." != "$rm_dir" ] && [ '..' != "$rm_dir" ]; then
+            rm -r "$rm_dir"
+        fi
     fi
     rm "$remove_file.conf" "$remove_file.conf.bak"
     if $ssl; then
@@ -277,8 +286,9 @@ else
     #create info.php
     [ ! -f "$dr"/info.php ] && echo "$tphp" > "$dr"/info.php && printf "\n\tinfo.php created\n" || printf "\n\tinfo.php exists (skipped)\n"
     chown $user:$user "$dr"/info.php
+    chmod 640 "$dr"/info.php
 
-    dire_opts="\n\t\tAllowOverride All\n\t\tOptions Indexes FollowSymLinks MultiViews\n\t\tOrder allow,deny\n\t\tRequire all granted\n\t\tAllow from all\n\t\t\n\t"
+    dire_opts="\n\t\tAllowOverride All\n\t\tOptions Indexes FollowSymLinks MultiViews\n\t\tRequire all granted\n\t"
     dire="\t<Directory $dr>$dire_opts</Directory>\n"
 
     #custom sites
@@ -401,10 +411,14 @@ else
 fi
 
 #restart the apache2 service
-{
-service apache2 restart ||
-systemctl restart apache2
-} &&
-echo "$endm" ||
-echo "\n\tE: Failed to restart apache2\n"
+if ! $nsr; then
+    {
+    service apache2 restart ||
+    systemctl restart apache2
+    } &&
+    echo "$endm" ||
+    echo "\n\tE: Failed to restart apache2\n"
+else
+    echo "$endm after restarting the server."
+fi
 
